// ─────────────────────────────────────────────────────────────────────────────
// Core GraphQL domain types for GraphQL Hunter
// Raw traffic types + Day 2 analysis types all live here to avoid circular
// module imports between types/graphql.ts ↔ types/analysis.ts.
// ─────────────────────────────────────────────────────────────────────────────

// ── Operation classification ──────────────────────────────────────────────────

export type OperationType = 'query' | 'mutation' | 'subscription' | 'unknown';

export type RiskLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';

// ── Day 2: Analysis types ─────────────────────────────────────────────────────

/** A single field access extracted from the parsed query AST. */
export interface FieldAccess {
  fieldName: string;
  /** true when any argument on this field matches an ID pattern. */
  hasIdArg:  boolean;
}

/** A single security finding produced by the risk scorer. */
export interface RiskFinding {
  level:  RiskLevel;
  title:  string;
  detail: string;
}

/** Analysis result for one GraphQL operation. */
export interface QueryAnalysis {
  operationType: OperationType;
  operationName: string;
  fields:        FieldAccess[];
  variables:     string[];
  findings:      RiskFinding[];
  /** Highest risk level among all findings. */
  riskLevel:     RiskLevel;
  fieldCount:    number;
}

/** Analysis result for a full captured request (single or batched). */
export interface RequestAnalysis {
  operations:  QueryAnalysis[];
  overallRisk: RiskLevel;
}

// ── Raw GraphQL wire format ───────────────────────────────────────────────────

/** A single GraphQL request body as sent over the wire. */
export interface GraphQLRequestBody {
  query: string;
  variables?:     Record<string, unknown>;
  operationName?: string;
  extensions?:    Record<string, unknown>;
}

/** A GraphQL error returned from the server. */
export interface GraphQLError {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?:       Array<string | number>;
  extensions?: Record<string, unknown>;
}

/** A GraphQL response body as received from the server. */
export interface GraphQLResponseBody {
  data?:       Record<string, unknown> | null;
  errors?:     GraphQLError[];
  extensions?: Record<string, unknown>;
}

// ── Captured traffic ─────────────────────────────────────────────────────────

/** The response captured via filterResponseData. */
export interface CapturedResponse {
  status:          number;
  statusText:      string;
  responseHeaders: Record<string, string>;
  /** Parsed JSON body — may be single response or array (batched). */
  body:            GraphQLResponseBody | GraphQLResponseBody[];
  timestamp:       number;
  /** Round-trip time from request sent to response fully received (ms). */
  durationMs:      number;
}

/**
 * A fully captured GraphQL request + response pair.
 * `response` is undefined until the response body has been received.
 */
export interface CapturedRequest {
  /** Unique ID generated by the extension (crypto.randomUUID). */
  id:              string;
  /** Browser's requestId — used to correlate request/response in webRequest API. */
  requestId:       string;
  url:             string;
  /** The tab that originated the request. -1 if unknown. */
  tabId:           number;
  /** Unix timestamp (ms) when the request was first seen. */
  timestamp:       number;
  method:          string;
  requestHeaders:  Record<string, string>;
  /** Parsed body — single operation or array for batched requests. */
  body:            GraphQLRequestBody | GraphQLRequestBody[];
  /** true when `body` is an array (GraphQL batching). */
  isBatch:         boolean;
  /** Populated once the full response body has been captured. */
  response?:   CapturedResponse;
  /** Populated by the Day 2 query analyzer immediately after capture. */
  analysis?:   RequestAnalysis;
}

// ── Storage helpers ───────────────────────────────────────────────────────────

/** Aggregate stats displayed in the popup. */
export interface HunterStats {
  totalRequests: number;
  endpoints:     string[];
  batchCount:    number;
  mutationCount: number;
  queryCount:    number;
  riskCount:     number;
}
