// ─────────────────────────────────────────────────────────────────────────────
// Core GraphQL domain types for GraphQL Hunter
// Raw traffic types + Day 2 analysis types + Day 3 schema/complexity types
// + Day 4 authorization testing + response-comparison types
// + Day 5 finding/evidence management types
// all live here to avoid circular module imports.
// ─────────────────────────────────────────────────────────────────────────────

// ── Operation classification ──────────────────────────────────────────────────

export type OperationType = 'query' | 'mutation' | 'subscription' | 'unknown';

export type RiskLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';

// ── Day 2 + 3: Analysis types ────────────────────────────────────────────────

/** A single field access extracted from the parsed query AST. */
export interface FieldAccess {
  fieldName: string;
  /** true when any argument on this field matches an ID pattern. */
  hasIdArg:  boolean;
}

/** A single security finding produced by the risk scorer. */
export interface RiskFinding {
  level:  RiskLevel;
  title:  string;
  detail: string;
}

/** Analysis result for one GraphQL operation. */
export interface QueryAnalysis {
  operationType: OperationType;
  operationName: string;
  fields:        FieldAccess[];
  variables:     string[];
  findings:      RiskFinding[];
  /** Highest risk level among all findings. */
  riskLevel:     RiskLevel;
  fieldCount:    number;
  /** Day 3: nesting depth + cost estimate. */
  complexity?:   ComplexityScore;
}

// ── Day 3: Complexity score ──────────────────────────────────────────────────

/** Query complexity score derived from depth, field count and list multipliers. */
export interface ComplexityScore {
  /** Maximum nesting depth of selection sets. */
  depth:            number;
  fieldCount:       number;
  /** Estimated server-side cost (depth × field count heuristic). */
  estimatedCost:    number;
  /** True when cost exceeds the HIGH-risk threshold (depth > 5 or cost > 100). */
  isHighComplexity: boolean;
}

// ── Day 3: Schema model ───────────────────────────────────────────────────────

/** A single field observed on a reconstructed schema type. */
export interface SchemaField {
  /** Argument names seen on this field across all captures. */
  args:             string[];
  /** Operation types in which this field was observed. */
  seenInOps:        OperationType[];
  /** How many times this field has been observed. */
  observationCount: number;
}

/** A reconstructed type node in the partial schema model. */
export interface SchemaType {
  /** Inferred type name (top-level field name used as proxy). */
  typeName: string;
  /** Map of fieldName → SchemaField metadata. */
  fields:   Record<string, SchemaField>;
}

/**
 * Incrementally-built partial schema model derived from observed traffic.
 * No introspection required — reconstructed purely from captured ASTs.
 */
export interface SchemaModel {
  /** Map of rootFieldName → SchemaType. */
  types:       Record<string, SchemaType>;
  /** Distinct GraphQL endpoint URLs observed. */
  endpoints:   string[];
  lastUpdated: number;
}

/** Analysis result for a full captured request (single or batched). */
export interface RequestAnalysis {
  operations:  QueryAnalysis[];
  overallRisk: RiskLevel;
}

// ── Raw GraphQL wire format ───────────────────────────────────────────────────

/** A single GraphQL request body as sent over the wire. */
export interface GraphQLRequestBody {
  query: string;
  variables?:     Record<string, unknown>;
  operationName?: string;
  extensions?:    Record<string, unknown>;
}

/** A GraphQL error returned from the server. */
export interface GraphQLError {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?:       Array<string | number>;
  extensions?: Record<string, unknown>;
}

/** A GraphQL response body as received from the server. */
export interface GraphQLResponseBody {
  data?:       Record<string, unknown> | null;
  errors?:     GraphQLError[];
  extensions?: Record<string, unknown>;
}

// ── Captured traffic ─────────────────────────────────────────────────────────

/** The response captured via filterResponseData. */
export interface CapturedResponse {
  status:          number;
  statusText:      string;
  responseHeaders: Record<string, string>;
  /** Parsed JSON body — may be single response or array (batched). */
  body:            GraphQLResponseBody | GraphQLResponseBody[];
  timestamp:       number;
  /** Round-trip time from request sent to response fully received (ms). */
  durationMs:      number;
}

/**
 * A fully captured GraphQL request + response pair.
 * `response` is undefined until the response body has been received.
 */
export interface CapturedRequest {
  /** Unique ID generated by the extension (crypto.randomUUID). */
  id:              string;
  /** Browser's requestId — used to correlate request/response in webRequest API. */
  requestId:       string;
  url:             string;
  /** The tab that originated the request. -1 if unknown. */
  tabId:           number;
  /** Unix timestamp (ms) when the request was first seen. */
  timestamp:       number;
  method:          string;
  requestHeaders:  Record<string, string>;
  /** Parsed body — single operation or array for batched requests. */
  body:            GraphQLRequestBody | GraphQLRequestBody[];
  /** true when `body` is an array (GraphQL batching). */
  isBatch:         boolean;
  /** Populated once the full response body has been captured. */
  response?:   CapturedResponse;
  /** Populated by the Day 2/3 query analyzer immediately after capture. */
  analysis?:   RequestAnalysis;
  /** Day 4: auth-test runs executed against this request. */
  authTests?:  AuthTestResult[];
}

// ── Day 4: Authorization testing ─────────────────────────────────────────────

/**
 * Which auth-stripping strategy to run.
 *   NO_AUTH       — remove Authorization header AND cookies
 *   STRIP_COOKIES — remove only cookies (token may live in header)
 *   MUTATE_ID     — replay with every ID variable ±1 (BOLA/IDOR probe)
 */
export type AuthTestType = 'NO_AUTH' | 'STRIP_COOKIES' | 'MUTATE_ID';

/**
 * Server's enforcement verdict after comparing original vs. replayed responses.
 *   VULNERABLE    — server returned data without credentials (auth bypass)
 *   PROTECTED     — server rejected or returned empty data
 *   INCONCLUSIVE  — cannot determine (CORS block, network error, same response)
 */
export type AuthVerdict = 'VULNERABLE' | 'PROTECTED' | 'INCONCLUSIVE';

/** A single field-level diff between the original and replayed responses. */
export interface ResponseDiffEntry {
  /** Dot-path to the field (e.g. "data.user.email"). */
  path:           string;
  originalValue:  unknown;
  replayedValue:  unknown;
  /** true when originalValue !== replayedValue (deep equality). */
  changed:        boolean;
}

/** Full diff result between an original and a replayed GraphQL response. */
export interface ResponseDiff {
  entries:       ResponseDiffEntry[];
  /** Fields that appeared in replayed response but were null/absent in original. */
  leakedFields:  string[];
  /** true when ALL compared fields are identical (no change detected). */
  fullyIdentical: boolean;
}

/** Result of a single auth-test run against a captured request. */
export interface AuthTestResult {
  id:                string;
  /** ID of the CapturedRequest this test was run against. */
  requestId:         string;
  testType:          AuthTestType;
  testedAt:          number;
  verdict:           AuthVerdict;
  diff:              ResponseDiff;
  /** HTTP status returned by the replayed request. */
  replayedStatus:    number;
  replayedDurationMs: number;
  /** Human-readable summary of why the verdict was assigned. */
  evidence:          string;
}

// ── Day 5: Finding & Evidence Management ─────────────────────────────────────

/**
 * Numeric severity rank used for sorting and triage.
 *   0 = PROTECTED  (no vulnerability found)
 *   1 = INCONCLUSIVE (couldn't determine)
 *   2 = VULNERABLE  (confirmed auth bypass)
 */
export type SeverityScore = 0 | 1 | 2;

/**
 * A persisted finding — wraps an AuthTestResult with additional context
 * (request URL, operation name, pre-computed severity score, user note, curl).
 * Stored independently from CapturedRequest so it survives CLEAR_REQUESTS.
 */
export interface Finding {
  /** Unique finding ID (same as AuthTestResult.id). */
  id:            string;
  /** ID of the originating CapturedRequest (may no longer be in storage). */
  requestId:     string;
  /** Full GraphQL endpoint URL of the original request. */
  requestUrl:    string;
  /** Primary operation name (or 'anonymous'). */
  operationName: string;
  /** The full auth-test result. */
  result:        AuthTestResult;
  /** Pre-computed numeric severity for sorting. */
  severityScore: SeverityScore;
  /** Optional analyst note attached by the user. */
  note:          string;
  /** Pre-generated curl command reproducing the replayed request. */
  curl:          string;
}

/** Top-level shape of the dedicated findings storage slot. */
export interface FindingsStore {
  findings:    Finding[];
  lastUpdated: number;
}

// ── Storage helpers ───────────────────────────────────────────────────────────

/** Aggregate stats displayed in the popup and dashboard. */
export interface HunterStats {
  totalRequests:    number;
  endpoints:        string[];
  batchCount:       number;
  mutationCount:    number;
  queryCount:       number;
  riskCount:        number;
  /** Day 5: finding verdict counts */
  vulnerableCount:  number;
  inconclusiveCount: number;
  protectedCount:   number;
}
